import type { MetadataRoute } from "next";

const BASE_URL = "https://asuransibekasi.id";

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  const productPages = [
    "/asuransi-kendaraan",
    "/asuransi-kendaraan/mobil",
    "/asuransi-kendaraan/bus",
    "/asuransi-kendaraan/truk-kendaraan-niaga",
    "/asuransi-properti",
    "/asuransi-properti/property-all-risk",
    "/asuransi-properti/kebakaran",
    "/asuransi-properti/gudang",
    "/asuransi-properti/pabrik",
    "/asuransi-properti/rumah",
    "/asuransi-liability",
    "/asuransi-liability/public-liability",
    "/asuransi-liability/limbah-b3",
    "/asuransi-engineering",
    "/asuransi-engineering/contractor-all-risk",
    "/asuransi-engineering/cecr",
    "/asuransi-machinery",
    "/asuransi-machinery/machinery-breakdown",
    "/asuransi-machinery/alat-berat",
    "/asuransi-kargo",
    "/asuransi-kargo/kargo-darat",
    "/asuransi-kargo/marine-cargo",
    "/asuransi-surety-bond",
    "/asuransi-surety-bond/jaminan-penawaran",
    "/asuransi-surety-bond/jaminan-pelaksanaan",
    "/asuransi-surety-bond/jaminan-uang-muka",
    "/asuransi-surety-bond/jaminan-pemeliharaan",
    "/asuransi-surety-bond/custom-bond-ob23",
    "/artikel",
    "/artikel/kenapa-perumahan-bekasi-timur-rawan-banjir-musiman",
    "/artikel/panduan-asuransi-pabrik-jababeka",
    "/artikel/par-vs-kebakaran-gudang-bekasi",
    "/artikel/kesalahan-nilai-pertanggungan-rumah-bekasi",
    "/artikel/panduan-asuransi-ruko-bekasi",
    "/artikel/kenapa-pabrik-kawasan-industri-bekasi-wajib-public-liability",
    "/artikel/aturan-limbah-b3-pp-22-2021-industri-manufaktur-bekasi",
    "/artikel/studi-kasus-tuntutan-pencemaran-lingkungan-bekasi",
    "/artikel/incoterms-fob-vs-cif-siapa-wajib-asuransikan-barang-impor",
    "/artikel/panduan-marine-cargo-importir-bahan-baku-kawasan-industri-bekasi",
    "/artikel/kenapa-ekspedisi-truk-perlu-asuransi-kargo-terpisah-dari-asuransi-kendaraan",
    "/artikel/all-risk-vs-tlo-mobil-baru-bekasi",
    "/artikel/panduan-asuransi-truk-ekspedisi-jababeka-mm2100",
    "/artikel/biaya-asuransi-mobil-listrik-bekasi",
    "/artikel/wajibkah-bus-karyawan-passenger-liability",
    "/artikel/cara-klaim-asuransi-mobil-banjir-bekasi",
    "/artikel/kenapa-kontraktor-bekasi-butuh-surety-bond-sebelum-tender",
    "/artikel/syarat-surety-bond-proyek-bekasi",
    "/artikel/cara-mengurus-surety-bond-bekasi-tanpa-menghambat-tender",
    "/artikel/kesalahan-pengajuan-surety-bond-kontraktor-bekasi",
    "/artikel/tips-memilih-penerbit-surety-bond-bekasi",
  ];
  return [
    {
      url: BASE_URL,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 1,
    },
    ...productPages.map((path) => ({
      url: `${BASE_URL}${path}`,
      lastModified: now,
      changeFrequency: "monthly" as const,
      priority: ["/asuransi-properti", "/asuransi-liability", "/asuransi-kendaraan", "/asuransi-engineering", "/asuransi-machinery", "/asuransi-kargo", "/asuransi-surety-bond", "/artikel"].includes(path) ? 0.9 : 0.8,
    })),
  ];
}
